### PR TITLE
Update index_history with json payload as per the new NSE API Server

### PR DESCRIPTION
**Pull request by mraj602**
Update index_history with JSON payload as per the new NSE API Server. Changed the structure of the request sent to the server after testing it with the new NSE API. Added cinfo and index object data, which the API uses to access the internal data.

### CODE REVIEW

**Comment by buzzvolt** [comment]
hope this one does not see the fate of https://github.com/aeron7/nsepython/pull/40

**Comment by ramit-mitra** [comment]
Unfortunately the issue still persists with this patch. Still getting the `KeyError 'd'` with both `nsepythonserver` and `nsepython`.

**Comment by mraj602** [comment]
Merged with aeron7:master as the resolution is the same.

**Comment by mraj602** [comment]
> Unfortunately the issue still persists with this patch. Still getting the `KeyError 'd'` with both `nsepythonserver` and `nsepython`.

The issue is from the server. Even the request on [nifty indices website](https://www.niftyindices.com/reports/historical-data) returns no result. Might be a temporary issue. Hopefully, NSE will not change its structure again.

**Comment by ramit-mitra** [comment]
> > Unfortunately the issue still persists with this patch. Still getting the `KeyError 'd'` with both `nsepythonserver` and `nsepython`.
> 
> The issue is from the server. Even the request on [nifty indices website](https://www.niftyindices.com/reports/historical-data) returns no result. Might be a temporary issue. Hopefully, NSE will not change its structure again.

yeah, it seems they made some changes which broke the endpoint. 

```
{
    "Message": "Object reference not set to an instance of an object.",
    "StackTrace": "   at System.Data.RBTree`1.Successor(Int32\u0026 nodeId, Int32\u0026 mainTreeNodeId)\r\n   at System.Data.RBTree`1.RBTreeEnumerator.MoveNext()\r\n   at Newtonsoft.Json.Converters.DataTableConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)\r\n   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)\r\n   at IISL.Backpage.getHistoricaldatatabletoString(String cinfo) in D:\\NseIndices\\Temp\\March07_2024_LiveBackup\\Nifty Indices New\\Backpage.aspx.cs:line 420",
    "ExceptionType": "System.NullReferenceException"
}
```

**Pull request closed without merging**
